soumission-service:
    build: ../soumission-service
    container_name: soumission-service
    ports:
      - "8004:8004"
    environment:
      # DEV MODE ACTIVATED
      - SPRING_PROFILES_ACTIVE=dev
      - security.dev-fallback.enabled=true
      - DB_HOST=al-mizan-mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=soumission_db 
      # Allows Hibernate to auto-create/update tables in Dev
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  
      - REDIS_HOST=al-mizan-redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=al-mizan-rabbitmq
      - RABBITMQ_PORT=5672
      - MINIO_ENDPOINT=http://al-mizan-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=al-mizan-docs
      - AO_SERVICE_URL=http://appel-offres-service:8003
      - USER_SERVICE_URL=http://users-service:3002
      - DOCUMENT_SERVICE_URL=http://documents-service:8005
    networks:
      - al-mizan-network
    restart: unless-stopped

  evaluation-service:
    build: ../evaluation-service
    container_name: evaluation-service
    ports:
      - "8006:8008" 
    environment:
      # DEV MODE ACTIVATED
      - NODE_ENV=development 
      - PORT=8008
      - DB_HOST=al-mizan-mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=evaluation_db
      - RABBITMQ_URL=amqp://guest:guest@al-mizan-rabbitmq:5672
      - MINIO_ENDPOINT=al-mizan-minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - al-mizan-network
    restart: unless-stopped

  commission-service:
    build: ../commission-service
    container_name: commission-service
    ports:
      - "8007:8007"
    environment:
      # DEV MODE ACTIVATED
      - NODE_ENV=development
      - PORT=8007
      - DB_HOST=al-mizan-mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=commission_db
      - RABBITMQ_URL=amqp://guest:guest@al-mizan-rabbitmq:5672
      - MINIO_ENDPOINT=al-mizan-minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - al-mizan-network
    restart: unless-stopped